bind = "127.0.0.1:25567"

[forwarding]
method = "MODERN"
secret = "VEPZp3dbw5h4"

welcome_message = ""
action_bar = "<gold>Добро пожаловать на NeverSMP!</gold>"

[title]
enabled = true
title = "<aqua><bold>Добро пожаловать!</bold></aqua>"
subtitle = "<white>Рады всем игрокам</white>"
fade_in = 10
stay = 70
fade_out = 20

[boss_bar]
enabled = true
title = "<gold><bold>Добро пожаловать на NeverSMP!</bold></gold>"
health = 1.0
color = "yellow"
division = 0

[server_list]
reply_to_status = true
max_players = 100
message_of_the_day = "<gold><bold>NeverSMP</bold></gold>\n<gray>Добро пожаловать! Заходи, познакомимся!</gray>"
show_online_player_count = true
server_icon = "server-icon.png"