on load:
    set {obsi_tnt_item} to tnt named "&c&lОбси-ТНТ" with lore "&7Может взрывать обсидиан!"

command /giveobsitnt <player> <integer>:
    permission: op
    trigger:
        give arg-2 of {obsi_tnt_item} to arg-1

on place of tnt:
    if name of player's tool is "&c&lОбси-ТНТ":
        set {_x} to floor(x-coordinate of event-block)
        set {_y} to floor(y-coordinate of event-block)
        set {_z} to floor(z-coordinate of event-block)
        set {obsi_tnt::%{_x}%_%{_y}%_%{_z}%} to true

on break of tnt:
    set {_x} to floor(x-coordinate of event-block)
    set {_y} to floor(y-coordinate of event-block)
    set {_z} to floor(z-coordinate of event-block)
    if {obsi_tnt::%{_x}%_%{_y}%_%{_z}%} is true:
        delete {obsi_tnt::%{_x}%_%{_y}%_%{_z}%}
        cancel event
        set event-block to air
        drop 1 of {obsi_tnt_item} at event-location

on spawn of primed tnt:
    set {_x} to floor(x-coordinate of event-entity)
    set {_y} to floor(y-coordinate of event-entity)
    set {_z} to floor(z-coordinate of event-entity)
    if {obsi_tnt::%{_x}%_%{_y}%_%{_z}%} is true:
        delete {obsi_tnt::%{_x}%_%{_y}%_%{_z}%}
        set metadata value "obsi" of event-entity to true

on explode:
    if metadata value "obsi" of event-entity is true:
        loop blocks in radius 1.5 around event-location:
            if loop-block is obsidian:
                add loop-block to exploded blocks
